### ISSUE TITLE
query action-table results are all lower case

### ISSUE THREAD

**Issue by jlongman** [salesforce/policy_sentry#118]
BTW, thanks for this, I'm really hoping it will help with some of the crud (heh) we're dealing with.

I'm trying to generate a policy that very broadly allows (or disallows) tagging  (ie various operations) across "all" resources given a condition (say tag `c7n:admin:*`) and I'm finding appending the slightly cleaned output of the action-table into the write-policy fails.

Steps are:

- `docker run -v /here:/tmp -i --rm kmcquade/policy_sentry:latest "create-template --name myRole --output-file /tmp/tmp2.yml --template-type actions"`
- `docker run -v /here:/tmp -i --rm kmcquade/policy_sentry:latest "query action-table  --service all --access-level tagging --fmt yaml" >> /here/tmp2.yml`
- manually clean up the `/here/tmp2.yml` file to remove the preamble from the query
- `cat /here/tmp2.yml | docker run -i --rm kmcquade/policy_sentry:latest "write-policy"`
output:
```
Traceback (most recent call last):
  File "/usr/local/bin/policy_sentry", line 26, in <module>
    policy_sentry()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/policy_sentry/command/write_policy.py", line 63, in write_policy
    policy = write_policy_with_template(db_session, cfg, minimize)
  File "/usr/local/lib/python3.7/site-packages/policy_sentry/command/write_policy.py", line 90, in write_policy_with_template
    policy = sid_group.process_template(db_session, cfg, minimize)
  File "/usr/local/lib/python3.7/site-packages/policy_sentry/writing/sid_group.py", line 328, in process_template
    self.add_by_list_of_actions(db_session, cfg["actions"])
  File "/usr/local/lib/python3.7/site-packages/policy_sentry/writing/sid_group.py", line 252, in add_by_list_of_actions
    db_session, [item["resource_arn_format"]], item["access_level"]
  File "/usr/local/lib/python3.7/site-packages/policy_sentry/writing/sid_group.py", line 136, in add_by_arn_and_access_level
    db_session, raw_arn_format
  File "/usr/local/lib/python3.7/site-packages/policy_sentry/querying/arns.py", line 111, in get_resource_type_name_with_raw_arn
    resource_type_name = str(result.resource_type_name)
AttributeError: 'NoneType' object has no attribute 'resource_type_name'
```
changed to add a try except output:
```
arn:${Partition}:dms:${Region}:${Account}:cert:
'NoneType' object has no attribute 'resource_type_name'
```

If I just do it with `a4b:createtag` then the case works in both with proper case and all lowercase.  It appears to be the full set.   

(Is this related to #114?  Is there a workaround.)

**Comment by kmcquade** [comment]
@jlongman - I'm glad you like it! Thanks for providing feedback, I really appreciate it. 

#### The bug

Hmmm. This is very weird. I did some major refactoring between versions 0.6.11 and 0.7.0. Turns out your policy works fine in 0.6.11 (note: It has a different template format). I tried debugging this a bit for 0.7.0. I'm not sure what the error is and I'll have to dive into it a bit more. 

I don't think it has to do with the lowercase output. I made an effort to normalize all IAM actions by setting them to lowercase because it seemed like things would just get too crazy.

#### Large tagging policies

So, you want this to be across **all** resources, not per-ARN, right? Why not just feed the output of the query command into your JSON policy file?

In an effort to show why you wouldn't want to use the write-policy function for creating those policies, I put together this file for you. 

Using the `--minimize 0` argument: https://gist.github.com/kmcquade/5bdb5368d9e9f4f8e63469786fc7fd82

Without minimization: https://gist.github.com/kmcquade/3440c935311012c08d8aa5ed5539460f

**Comment by kmcquade** [comment]
Regarding the bug - I just figured it out. I'm pushing the fix so there should be a new release out for it shortly.

**Comment by jlongman** [comment]
Wow! Thank you!  What an amazing response.

To be honest I’m still learning what policy_sentry has to offer and trying to get a feel for how it will work in our workflow so maybe missed the simple path.

Fantastic! I’ll poke around some more soon.

**Comment by kmcquade** [comment]
For sure! Let me know if you have any questions. I’m available on the Gitter channel as well.

I’m super glad you brought this one up too. It was absolutely an issue with the move from 0.6.11 to 0.7.0, and not something with you. Glad the issue didn’t linger for longer than a day. 

Regarding how you’ll use it in your workflow - are you planning on using this for semi-automation (automating what someone did manually but still with humans), as a python library, in a CICD pipeline (terraform), or perhaps something else? Those are some of the cases I’ve heard.

I am particularly interested in how I can improve the Terraform module, as I think that offers the most potential - like perhaps turning it into a GitHub action to kick off IAM policy creation in Terraform cloud, for example. Happy to discuss ideas or use cases in Gitter.
